### ISSUE TITLE
Increase robustness of the databroker

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/AgentLib#3]
We now had the case of a failing agent due to too many callbacks in the databroker. 
Features I am missing:

- debug the current queue size, if it is above a certain threshold or keeps getting bigger
- maybe set a max qsize (would require `Queue` instead of `SimpleQueue`
- Execute the callbacks in threads

I will create a branch and add minimal examples which show the limitations of the databroker. 
I think we should also check how other brokers (e.g. mqtt) handle these cases.

**Comment by FWuellhorst** [comment]
I added some worst-case examples in examples\databroker_limits.py. 
While the logging is easy to implement, the threading option is a design choice we have to make: If a callback fails, should the agent continue living? Do we really need the overhead of creating threads for each message?

**Comment by tstorek** [comment]
@FWuellhorst @EserSteffen instead of using expensive threading. How about asyncio wrapping the callback functions? Basically, it does the same as threading but does not care about any order (https://docs.python.org/3/library/asyncio-sync.html). Hence, all callbacks `must` be independent and only event triggered, alternatively. One could use Simpy's events. However, I am not sure how intuitive to implement the latter are.

@FWuellhorst: How can the DataBroker organize the order of file access? Isn't it more about cleanly read and write files? Hence, FileAccess should happen with a waiting functionality. Maybe this one can help: https://superfastpython.com/aiofiles-for-asyncio-in-python/

Asyncio is most likely the most efficient way to achieve your goal.
